=== helisma/atividades-pos-2024/xsd/cardapio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
xmlns:xs="http://umcardapio.org"
targetNamespace="http://umcardapio.org"
elementFormDefault="qualified">

<simpleType name="precoType">
    <restriction base="string">
        <pattern value="\d+,\d{2};"/>
    </restriction>
</simpleType>

    <element name="cardapio">
        <complexType>
            <sequence>
                <element name="prato" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="nome" type="string"/>
                            <element name="descricao" type="string"/>
                            <element name="ingredientes">
                                <complexType>
                                    <sequence>
                                        <element name="ingrediente" type="string" maxOccurs="unbounded"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="preco" type="precoType"/>
                            <element name="calorias" type="integer"/>
                            <element name="tempopreparo" type="string"/>
                        </sequence>
                        <attribute name="prato" type="integer" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>

</schema>

=== helisma/atividades-pos-2024/xsd/cardapio.xml
<?xml version="1.0" encoding="utf-8"?>

<cardapio xmlns="http://umcardapio.org" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://umcardapio.org cardapio.xsd">
    <prato id="P01">
        <nome>Lasanha</nome>
        <descricao>Lasanha com queijo</descricao>
        <ingredientes>
            <ingrediente>macarrao</ingrediente>
            <ingrediente>molho de tomate</ingrediente>
            <ingrediente>creme de leite</ingrediente>
            <ingrediente>queijo</ingrediente>
            <ingrediente>carne moida</ingrediente>
        </ingredientes>
        <preco moeda="BRL">7,00&reais;</preco>    
        <calorias>2.000</calorias>
        <tempopreparo>30 min</tempopreparo>    
    </prato>

    <prato id="P02">
        <nome>salada de frutas</nome>
        <descricao>frutas picadas com leite condensado</descricao>
        <ingredientes>
            <ingrediente>frutas da sua preferencia</ingrediente>
            <ingrediente>leite condensado</ingrediente>
        </ingredientes>
        <preco moeda="BRL">05,00&reais;</preco>    
        <calorias>700</calorias>
        <tempopreparo>10 min</tempopreparo>    
    </prato>

    <prato id="P03">
        <nome>feijoada</nome>
        <descricao>feijao preto com temperos e carnes</descricao>
        <ingredientes>
            <ingrediente>feijão preto</ingrediente>
            <ingrediente>carnes da sua preferencia</ingrediente>
            <ingrediente>temperos da sua preferencia</ingrediente>
        </ingredientes>
        <preco moeda="BRL">12,00&reais;</preco>    
        <calorias>1000</calorias>
        <tempopreparo>1 hora</tempopreparo>    
    </prato>

    <prato id="P04">
        <nome>Tapioca</nome>
        <descricao>Tapioca com recheio de queijo e presunto</descricao>
        <ingredientes>
            <ingrediente>goma de tapioca</ingrediente>
            <ingrediente>queijo</ingrediente>
            <ingrediente>presunto</ingrediente>
        </ingredientes>
        <preco moeda="BRL">04,00&reais;</preco>    
        <calorias>90</calorias>
        <tempopreparo>15 min</tempopreparo>    
    </prato>

    <prato id="P05">
        <nome>Sopa de carne</nome>
        <descricao>sopa temperada com vegetais e carne</descricao>
        <ingredientes>
            <ingrediente>macarrão</ingrediente>
            <ingrediente>carne da sua preferencia</ingrediente>
            <ingrediente>e vegetais</ingrediente>
        </ingredientes>
        <preco moeda="BRL">8,00&reais;</preco>    
        <calorias>2000</calorias>
        <tempopreparo>30 min</tempopreparo>    
    </prato>    

</cardapio>
